"""empty message

Revision ID: a1501a1a6ef2
Revises: fb03c3ab0993
Create Date: 2020-12-15 22:12:02.540392

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1501a1a6ef2'
down_revision = 'fb03c3ab0993'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_data')
    op.add_column('users', sa.Column('_description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', '_description')
    op.create_table('users_data',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['users.id'], name='users_data_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='users_data_pkey')
    )
    # ### end Alembic commands ###
